[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build]
  command = "cd timetable_app && flutter build web --release"
  publish = "timetable_app/build/web"

[[plugins]]
  package = "netlify-plugin-flutter"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
